import fs from "fs";
import path from "path";
import url from "url";

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));

const INPUT_CSV_PATH = path.resolve(__dirname, "../../trades.csv");
const OUTPUT_CSV_PATH = path.resolve(__dirname, "../../trades_feedback.csv");

// Basic English stopwords to avoid counting trivial words as "valid"
const STOPWORDS = new Set([
	"a",
	"an",
	"and",
	"are",
	"as",
	"at",
	"be",
	"but",
	"by",
	"for",
	"if",
	"in",
	"into",
	"is",
	"it",
	"no",
	"not",
	"of",
	"on",
	"or",
	"such",
	"that",
	"the",
	"their",
	"then",
	"there",
	"these",
	"they",
	"this",
	"to",
	"was",
	"will",
	"with",
	"we",
	"you",
	"your",
	"our",
	"i",
	"me",
	"my",
	"mine",
	"ours",
	"yours",
]);

// Attempt to load a dictionary from the `word-list` package, if installed.
let wordSet = undefined;
try {
	const { default: wordListPath } = await import("word-list");
	const wordsTxt = fs.readFileSync(wordListPath, "utf8");
	wordSet = new Set(
		wordsTxt
			.split("\n")
			.map((w) => w.trim().toLowerCase())
			.filter((w) => w.length >= 3)
	);
	// eslint-disable-next-line no-console
	console.log(`Loaded dictionary with ${wordSet.size.toLocaleString()} words.`);
} catch (e) {
	// eslint-disable-next-line no-console
	console.warn(
		"Dictionary package 'word-list' not installed. Falling back to heuristic word check."
	);
}

function tokenizeWords(text) {
	if (!text) return [];
	// Extract alphabetic tokens only
	const tokens = text.toLowerCase().match(/[a-z]+/g);
	return tokens ? tokens : [];
}

function hasAtLeastOneValidWord(note) {
	const tokens = tokenizeWords(note).filter(
		(t) => t.length >= 3 && !STOPWORDS.has(t)
	);
	if (tokens.length === 0) return false;

	if (wordSet) {
		for (const token of tokens) {
			if (wordSet.has(token)) return true;
		}
		return false;
	}

	// Heuristic fallback: consider a token valid if it contains at least one vowel and isn't just repeated chars
	const hasVowel = /[aeiou]/;
	for (const token of tokens) {
		if (hasVowel.test(token)) {
			const first = token[0];
			if (!token.split("").every((ch) => ch === first)) {
				return true;
			}
		}
	}
	return false;
}

function parseCsvLineFlexible(line, expectedColumnsCount) {
	// The CSV was generated by joining values with commas without quoting.
	// We assume only the last field (note) can contain commas.
	const parts = line.split(",");
	if (parts.length < expectedColumnsCount) return null;
	const base = parts.slice(0, expectedColumnsCount - 1);
	const note = parts.slice(expectedColumnsCount - 1).join(",");
	return [...base, note];
}

function filterCsv(inputPath, outputPath) {
	if (!fs.existsSync(inputPath)) {
		throw new Error(`Input CSV not found at ${inputPath}`);
	}
	const raw = fs.readFileSync(inputPath, "utf8");
	const lines = raw.split(/\r?\n/).filter((l) => l.length > 0);
	if (lines.length === 0) {
		throw new Error("Input CSV is empty.");
	}

	const header = lines[0];
	const headers = header.split(",");
	const expectedColumnsCount = headers.length; // should be 10
	const noteIndex = headers.findIndex((h) => h.trim() === "note");
	if (noteIndex === -1) {
		throw new Error("CSV does not contain a 'note' column.");
	}

	const out = [header];
	let total = 0;
	let kept = 0;

	for (let i = 1; i < lines.length; i++) {
		const line = lines[i];
		if (!line.trim()) continue;
		total++;
		const row = parseCsvLineFlexible(line, expectedColumnsCount);
		if (!row) continue; // malformed line
		const note = row[noteIndex] ?? "";
		if (hasAtLeastOneValidWord(note) && note !== "system") {
			out.push(row.join(","));
			kept++;
		}
	}

	fs.writeFileSync(outputPath, out.join("\n"), "utf8");
	// eslint-disable-next-line no-console
	console.log(
		`Filtered ${kept}/${total} rows with meaningful notes -> ${outputPath}`
	);
}

filterCsv(INPUT_CSV_PATH, OUTPUT_CSV_PATH);
